#!/bin/sh

set -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/postinst.mysql 
dbc_generate_include=template:/etc/dataware/catalog_config.cfg
dbc_generate_include_args="-o template_infile=/usr/share/pyshared/dataware/catalog/catalog.cfg"
dbc_go dataware-catalog $@

#DEBHELPER#
